stages:
  preprocess_data:
    cmd: python src/eda_utils.py
    deps:
    - data/MachineLearningRating_v3.txt
    - src/eda_utils.py
    outs:
    - data/MachineLearningRating_v3_clean.csv
  prepare_modeling:
    cmd: python src/data_processing.py
    deps:
    - data/MachineLearningRating_v3_clean.csv
    - src/data_processing.py
    outs:
    - data/preprocessed_data.csv
  train_models:
    cmd: python src/modeling.py
    deps:
    - data/preprocessed_data.csv
    - src/modeling.py
    outs:
    - models
